version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: kwatapos_db
    environment:
      POSTGRES_USER: kwata_admin
      POSTGRES_PASSWORD: kwata_password
      POSTGRES_DB: kwatapos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
